### ISSUE TITLE
KeyError in clean_occurrences

### ISSUE THREAD

**Issue by zzeppozz** [specifysystems/lmpy#226]
## Describe the bug

When calling clean_occurrences with a correctly written wrangler config file containing the decimal_precision_filter, the code fails with a KeyError.

## To Reproduce
Call:  
clean_occurrences --species_key species_name --x_key x --y_key y  \
                   --report_filename ./output/cleaning_report.json \
                   ./input/heuchera.csv  \
                   ./output/clean_heuchera.csv \
                   ./input/wrangler_conf.json

## Expected behavior

No exception

## Desktop (please complete the following information)
Docker instance using specify-lmpy 3.1.2 installed with pip

## Additional context
Traceback (most recent call last):
  File "/usr/local/bin/clean_occurrences", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/lmpy/tools/clean_occurrences.py", line 120, in cli
    wranglers = wrangler_factory.get_wranglers(
  File "/usr/local/lib/python3.8/dist-packages/lmpy/data_wrangling/factory.py", line 63, in get_wranglers
    return [
  File "/usr/local/lib/python3.8/dist-packages/lmpy/data_wrangling/factory.py", line 64, in <listcomp>
    self.wrangler_types[config["wrangler_type"]].from_config(
KeyError: 'decimal_precision_filter'

**Comment by cjgrady** [comment]
The wrangler name is actually "DecimalPrecisionFilter".  #176 will hopefully prevent this problem in the future

**Comment by zzeppozz** [comment]
got it, code/config mismatch
