### ISSUE TITLE
specifying key_field parameter for split_occurrence_data causes exception

### ISSUE THREAD

**Issue by zzeppozz** [specifysystems/lmpy#341]
## Describe the bug

Specifying the key_field parameter in a config_file for split_occurrence_data throws exception:
Traceback (most recent call last):
  File "/usr/local/bin/split_occurrence_data", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/lmpy/tools/split_occurrence_data.py", line 135, in cli
    occurrence_processor.process_reader(reader, wranglers)
  File "/usr/local/lib/python3.8/dist-packages/lmpy/data_preparation/occurrence_splitter.py", line 168, in process_reader
    self.write_points(points)
  File "/usr/local/lib/python3.8/dist-packages/lmpy/data_preparation/occurrence_splitter.py", line 181, in write_points
    if writer_key not in self.writers.keys():
TypeError: unhashable type: 'list'

## To Reproduce

at a bash prompt, run split_occurrence_data --config_file=<path to config file>

with the config file 
{
    "max_open_writers": 100,
    "key_field": "scientificName",
    "dwca":  [
        ["/volumes/data/input/occ_heuchera_gbif.zip",
         "/volumes/data/config/wrangle_nothing.json"
        ]
    ],
    "out_dir": "/volumes/output"
}

## Expected behavior

No exception, executes correctly.

## Desktop (please complete the following information)

- linux
- Version 3.1.20

**Comment by cjgrady** [comment]
@zzeppozz is data available somewhere?  and what does the wrangler configuration file look like?
